In [37]:
import pandas as pd

In [38]:
data = pd.read_csv('nyc_real_estate.csv', index_col=False)

In [39]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 387 entries, 0 to 386
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       387 non-null    int64
 1   Name             387 non-null    object
 2   City             387 non-null    object
 3   Neighbourhood    387 non-null    object
 4   Price            387 non-null    object
 5   Year Built       387 non-null    object
 6   Beds             387 non-null    object
 7   Baths            387 non-null    object
 8   Area             387 non-null    object
 9   Price(per sqft)  387 non-null    object
 10  A/C              387 non-null    object
dtypes: int64(1), object(10)
memory usage: 33.4+ KB

In [40]:
data = data.drop(labels = ['Unnamed: 0'], axis = 1)

In [41]:
data = data.replace('Null', pd.NA).dropna()

In [42]:
data.head()

,Name,City,Neighbourhood,Price,Year Built,Beds,Baths,Area,Price(per sqft),A/C
1,37-26 32nd St #5K,"Long Island City, NY 11101",Astoria,"$620,000",Year Built: 2022,Studio,1 Bath,441 sqft,"$1,406",Cooling only
2,37-26 32nd St #3G,"Long Island City, NY 11101",Astoria,"$730,000",Year Built: 2022,1 Bed,1 Bath,579 sqft,"$1,261",Cooling only
3,37-26 32nd St #6L,"Long Island City, NY 11101",Astoria,"$570,000",Year Built: 2022,Studio,1 Bath,429 sqft,"$1,329",Cooling only
4,37-26 32nd St #3H,"Long Island City, NY 11101",Astoria,"$695,000",Year Built: 2022,1 Bed,1 Bath,632 sqft,"$1,100",No
6,2736 Independence Ave #6J,"Bronx, NY 10463",Spuyten Duyvil,"$235,995",Year Built: 1970,1 Bed,1 Bath,850 sqft,$278,No

In [43]:
data['cleaned_year'] = data['Year Built'].apply(lambda x : x[-4:])
data.head()

,Name,City,Neighbourhood,Price,Year Built,Beds,Baths,Area,Price(per sqft),A/C,cleaned_year
1,37-26 32nd St #5K,"Long Island City, NY 11101",Astoria,"$620,000",Year Built: 2022,Studio,1 Bath,441 sqft,"$1,406",Cooling only,2022
2,37-26 32nd St #3G,"Long Island City, NY 11101",Astoria,"$730,000",Year Built: 2022,1 Bed,1 Bath,579 sqft,"$1,261",Cooling only,2022
3,37-26 32nd St #6L,"Long Island City, NY 11101",Astoria,"$570,000",Year Built: 2022,Studio,1 Bath,429 sqft,"$1,329",Cooling only,2022
4,37-26 32nd St #3H,"Long Island City, NY 11101",Astoria,"$695,000",Year Built: 2022,1 Bed,1 Bath,632 sqft,"$1,100",No,2022
6,2736 Independence Ave #6J,"Bronx, NY 10463",Spuyten Duyvil,"$235,995",Year Built: 1970,1 Bed,1 Bath,850 sqft,$278,No,1970